import {money,normalize} from '../catalog-utils.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const key='dv-admin-catalog-v1';let data,view='dashboard',editing=null,timer;
const imageUrl=p=>/^https:\/\//.test(p.imageUrl)?p.imageUrl:'../'+p.imageUrl;
const validImage=url=>/^https:\/\/[^\s]+$/.test(url)||/^assets\/[\w./-]+\.(png|jpe?g|webp|svg)$/i.test(url)&&!url.includes('..');
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('#toast').classList.remove('show'),3200)}
function save(next){try{localStorage.setItem(key,JSON.stringify(next));data=next;$('#save-state').textContent='Rascunho salvo às '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});return true}catch{$('#form-error').textContent='Não foi possível salvar neste navegador. Libere espaço e tente novamente.';return false}}
function setView(name){view=name;document.querySelectorAll('.view').forEach(v=>v.hidden=true);$(name==='dashboard'?'#dashboard':name==='categories'?'#categories-view':name==='stores'?'#stores-view':'#catalog-view').hidden=false;document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('selected',b.dataset.view===name));$('#title').textContent=({dashboard:'Visão geral',products:'Produtos',offers:'Ofertas e destaques',categories:'Categorias',stores:'Nossas lojas'})[name];$('#subtitle').textContent=({dashboard:'Tudo o que você precisa para cuidar da sua loja.',products:'Organize seu catálogo, preços e disponibilidade.',offers:'Dê mais visibilidade aos produtos que fazem a diferença.',categories:'Um catálogo organizado facilita cada escolha.',stores:'Duas unidades. O mesmo cuidado.'})[name];render();}
function render(){const ps=data.products;$('#nav-count').textContent=ps.length;const offers=ps.filter(p=>p.badge||p.featured||p.oldPriceCents>p.priceCents);$('#stats').innerHTML=[['Produtos no catálogo',ps.length,'Todos os produtos cadastrados','▤'],['Produtos ativos',ps.filter(p=>p.active).length,'Disponíveis na vitrine','✓'],['Ofertas e destaques',offers.length,'Oportunidades para economizar','◇'],['Nossas unidades',2,'Solo Sagrado e Nature 1','⌖']].map(([title,count,note,icon])=>`<article class="stat"><i>${icon}</i><span>${title}</span><strong>${count}</strong><small>${note}</small></article>`).join('');$('#recent-products').innerHTML=[...ps].sort((a,b)=>(b.updatedAt||'').localeCompare(a.updatedAt||'')).slice(0,5).map(p=>`<div class="recent-row"><img src="${esc(imageUrl(p))}" alt=""><div><strong>${esc(p.name)}</strong><small>${esc(p.category)}</small></div><b>${money(p.priceCents)}</b><button data-edit="${p.id}" class="text-button">Editar</button></div>`).join('');$('#category-bars').innerHTML=data.categories.map(c=>{const n=ps.filter(p=>p.category===c.name).length;return `<div class="bars"><span>${esc(c.name)}</span><div class="bar"><div style="width:${ps.length?n/ps.length*100:0}%"></div></div><b>${n}</b></div>`}).join('');$('#category-cards').innerHTML=data.categories.map(c=>`<article class="category-card"><div class="category-icon">${esc(c.icon||'⊞')}</div><h2>${esc(c.name)}</h2><p>${ps.filter(p=>p.category===c.name).length} produtos · ${c.subcategories.length} subcategorias</p><ul>${c.subcategories.map(s=>`<li>${esc(s.name)}</li>`).join('')}</ul><button class="text-button" data-category="${esc(c.name)}">Ver produtos →</button></article>`).join('');renderTable()}
function renderTable(){let ps=data.products.filter(p=>(view!=='offers'||p.badge||p.featured||p.oldPriceCents>p.priceCents)&&(!$('#category-filter').value||p.category===$('#category-filter').value)&&($('#status-filter').value==='all'||p.active===($('#status-filter').value==='active'))&&normalize([p.name,p.brand,p.id].join(' ')).includes(normalize($('#search').value)));$('#result-count').textContent=`${ps.length} produtos encontrados`;$('#empty').hidden=!!ps.length;$('#rows').innerHTML=ps.map(p=>`<tr><td><img src="${esc(imageUrl(p))}" alt=""><div><strong>${esc(p.name)}</strong><small>#${p.id} · ${esc(p.variants.length?p.variants.length+' tamanhos':p.detail)}</small></div></td><td>${esc(p.category)}</td><td><strong>${money(p.priceCents)}</strong>${p.oldPriceCents>p.priceCents?`<small><del>${money(p.oldPriceCents)}</del></small>`:''}</td><td>${p.stockQuantity}</td><td><span class="badge ${p.active?'':'off'}">${p.active?'Ativo':'Inativo'}</span></td><td><button data-edit="${p.id}" class="text-button">Editar →</button></td></tr>`).join('')}
const form=$('#product-form');const field=name=>form.elements.namedItem(name);
function subcategories(selected=''){const category=data.categories.find(c=>c.name===field('category').value);field('subcategory').innerHTML='<option value="">Sem subcategoria</option>'+category.subcategories.map(s=>`<option ${s.name===selected?'selected':''}>${esc(s.name)}</option>`).join('')}
function variantRow(v={}){const row=document.createElement('div');row.className='variant';row.innerHTML=`<label>Tamanho<input data-field="size" value="${esc(v.size||'')}" required maxlength="15"></label><label>Unidades<input data-field="packageQuantity" type="number" min="1" step="1" required value="${v.packageQuantity||1}"></label><label>Estoque<input data-field="stockQuantity" type="number" min="0" step="1" required value="${v.stockQuantity||0}"></label><button type="button" aria-label="Remover tamanho">×</button>`;row.dataset.id=v.id||'';row.querySelector('button').onclick=()=>row.remove();$('#variants').append(row)}
function edit(id){editing=data.products.find(p=>p.id===id)||null;const p=editing||{name:'',brand:'',detail:'',priceCents:0,oldPriceCents:0,stockQuantity:0,badge:'',imageUrl:'',category:data.categories[0].name,subcategory:'',active:true,featured:false,availableStore1:true,availableStore2:true,variants:[]};form.reset();$('#form-error').textContent='';$('#editor-title').textContent=editing?'Editar produto':'Novo produto';for(const n of ['name','brand','detail','stockQuantity','badge','imageUrl','category'])field(n).value=p[n]??'';field('price').value=p.priceCents?p.priceCents/100:'';field('oldPrice').value=p.oldPriceCents?p.oldPriceCents/100:'';for(const n of ['active','featured','availableStore1','availableStore2'])field(n).checked=!!p[n];subcategories(p.subcategory);$('#variants').innerHTML='';p.variants.forEach(variantRow);previewImage();$('#editor').showModal()}
function previewImage(){const url=field('imageUrl').value.trim();$('#product-preview').hidden=!validImage(url);if(validImage(url))$('#product-preview').src=imageUrl({imageUrl:url})}
field('category').onchange=()=>subcategories();field('imageUrl').oninput=previewImage;$('#add-variant').onclick=()=>variantRow();$('#new-product').onclick=()=>edit();$('#close-editor').onclick=$('#cancel').onclick=()=>$('#editor').close();
form.onsubmit=event=>{event.preventDefault();const image=field('imageUrl').value.trim();if(!validImage(image)){$('#form-error').textContent='Informe uma imagem HTTPS ou um caminho válido em assets/.';return}const name=field('name').value.trim();if(!name){$('#form-error').textContent='Preencha o nome do produto.';return}const variants=[...$('#variants').children].map((row,i)=>({id:Number(row.dataset.id)||Date.now()+i,productId:editing?.id,size:row.querySelector('[data-field="size"]').value.trim(),packageQuantity:Number(row.querySelector('[data-field="packageQuantity"]').value),stockQuantity:Number(row.querySelector('[data-field="stockQuantity"]').value),sortOrder:i}));if(variants.some(v=>!v.size)||new Set(variants.map(v=>v.size.toUpperCase())).size!==variants.length){$('#form-error').textContent='Preencha tamanhos diferentes para cada variação.';return}const next=structuredClone(data);const id=editing?.id??Math.max(0,...data.products.map(p=>p.id))+1;const p={...(editing||{id,createdAt:new Date().toISOString(),sortOrder:0,tone:'amber'}),name,imageUrl:image,category:field('category').value,subcategory:field('subcategory').value,brand:field('brand').value.trim(),detail:field('detail').value.trim(),priceCents:Math.round(Number(field('price').value)*100),oldPriceCents:Math.round(Number(field('oldPrice').value||0)*100),stockQuantity:Number(field('stockQuantity').value),badge:field('badge').value.trim(),variants:variants.map(v=>({...v,productId:id})),updatedAt:new Date().toISOString()};for(const n of ['active','featured','availableStore1','availableStore2'])p[n]=field(n).checked;const index=next.products.findIndex(x=>x.id===id);if(index<0)next.products.push(p);else next.products[index]=p;if(save(next)){$('#editor').close();render();notify('Produto salvo no rascunho. O site público não foi alterado.')}};
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav)setView(nav.dataset.view);const editor=e.target.closest('[data-edit]');if(editor)edit(Number(editor.dataset.edit));const cat=e.target.closest('[data-category]');if(cat){$('#category-filter').value=cat.dataset.category;setView('products')}});for(const id of ['search','category-filter','status-filter'])$('#'+id).addEventListener('input',renderTable);
$('#export').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='catalog.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Catálogo exportado. A publicação será feita na etapa de integração.')};
try{const r=await fetch('../catalog.json');if(!r.ok)throw Error();data=await r.json();try{const draft=JSON.parse(localStorage.getItem(key));if(draft&&Array.isArray(draft.products)&&Array.isArray(draft.categories)){data=draft;$('#save-state').textContent='Rascunho recuperado deste navegador'}}catch{}$('#category-filter').innerHTML='<option value="">Todas as categorias</option>'+data.categories.map(c=>`<option>${esc(c.name)}</option>`).join('');field('category').innerHTML=data.categories.map(c=>`<option>${esc(c.name)}</option>`).join('');render()}catch{$('#subtitle').textContent='Não foi possível carregar o catálogo. Recarregue a página.';$('#new-product').disabled=true;$('#export').disabled=true;}
